package com.tokoko.spark.adbc

import java.io.File
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.Files
import scala.collection.mutable.ArrayBuffer
import scala.jdk.CollectionConverters._

/**
 * Collects what each engine suite observed and renders one cross-engine markdown report.
 * Every suite persists its own records, so running a single suite refreshes only its column.
 */
object DialectReport {

  val Accepted = "ok"
  val Rejected = "rejected"
  val Wrong = "wrong"
  val NotApplicable = "n/a"

  private case class Record(kind: String, key: String, subKey: String, value: String, detail: String)

  private val dir = new File("target/dialect-matrix")
  private val records = scala.collection.mutable.Map[String, ArrayBuffer[Record]]()

  private def clean(s: String): String = Option(s).getOrElse("").replaceAll("[\\t\\r\\n]+", " ").trim

  private def add(engine: String, r: Record): Unit = synchronized {
    val buf = records.getOrElseUpdate(engine, ArrayBuffer())
    buf.filterInPlace(x => !(x.kind == r.kind && x.key == r.key && x.subKey == r.subKey))
    buf += r
  }

  def probe(engine: String, group: String, name: String, sql: String, outcome: String, detail: String): Unit =
    add(engine, Record("probe", group, name, outcome, clean(sql) + "\u0001" + clean(detail)))

  def info(engine: String, key: String, value: String): Unit =
    add(engine, Record("info", key, "", clean(value), ""))

  def typeMapping(engine: String, logical: String, nativeType: String, sparkType: String): Unit =
    add(engine, Record("type", logical, "", clean(sparkType), clean(nativeType)))

  def gap(engine: String, test: String, reason: String, error: String): Unit =
    add(engine, Record("gap", test, "", clean(reason), clean(error).take(300)))

  def flush(engine: String): Unit = synchronized {
    dir.mkdirs()
    val lines = records.getOrElse(engine, ArrayBuffer()).map { r =>
      Seq(r.kind, r.key, r.subKey, r.value, r.detail).mkString("\t")
    }
    Files.write(new File(dir, s"$engine.tsv").toPath, lines.asJava, UTF_8)
    render()
  }

  private def load(): Map[String, Seq[Record]] =
    Option(dir.listFiles()).getOrElse(Array.empty[File]).filter(_.getName.endsWith(".tsv")).sortBy(_.getName).map { f =>
      val recs = Files.readAllLines(f.toPath, UTF_8).asScala.toSeq.map(_.split("\t", -1)).collect {
        case Array(kind, key, subKey, value, detail) => Record(kind, key, subKey, value, detail)
      }
      f.getName.stripSuffix(".tsv") -> recs
    }.toMap

  private def cell(s: String): String = s.replace("|", "\\|")

  private def symbol(outcome: String): String = outcome match {
    case Accepted => "✅"
    case Rejected => "❌"
    case Wrong => "⚠️"
    case NotApplicable => "–"
    case other => other
  }

  private def render(): Unit = {
    val all = load()
    val engines = all.keys.toSeq.sorted
    val out = new StringBuilder
    out ++= "# Dialect matrix\n\n"
    out ++= "Generated by `sbt driverTests/test`; one column per engine suite that has run.\n\n"

    out ++= "## Syntax probes\n\n"
    out ++= "Raw SQL sent straight through ADBC. ✅ accepted with the expected rows · ❌ rejected · " +
      "⚠️ ran but returned different rows · – not applicable (engine lacks the column type)\n\n"
    val probes = all.toSeq.flatMap { case (e, rs) => rs.filter(_.kind == "probe").map(e -> _) }
    val probeOrder = probes.map { case (_, r) => (r.key, r.subKey) }.distinct
    probeOrder.map(_._1).distinct.foreach { group =>
      out ++= s"### $group\n\n"
      out ++= "| probe | SQL | " + engines.mkString(" | ") + " |\n"
      out ++= "|---|---|" + engines.map(_ => ":-:").mkString("|") + "|\n"
      probeOrder.filter(_._1 == group).foreach { case (_, name) =>
        val forProbe = probes.filter { case (_, r) => r.key == group && r.subKey == name }
        val sql = forProbe.head._2.detail.split("\u0001", -1).head
        val cells = engines.map(e => forProbe.find(_._1 == e).map(p => symbol(p._2.value)).getOrElse(""))
        out ++= s"| ${cell(name)} | `${cell(sql)}` | ${cells.mkString(" | ")} |\n"
      }
      out ++= "\n"
    }

    val infoKeys = all.values.flatten.filter(_.kind == "info").map(_.key).toSeq.distinct
    if (infoKeys.nonEmpty) {
      out ++= "## Observed behaviour\n\n"
      out ++= "| | " + engines.mkString(" | ") + " |\n|---|" + engines.map(_ => "---").mkString("|") + "|\n"
      infoKeys.foreach { k =>
        val cells = engines.map(e => all(e).find(r => r.kind == "info" && r.key == k).map(r => cell(r.value)).getOrElse(""))
        out ++= s"| ${cell(k)} | ${cells.mkString(" | ")} |\n"
      }
      out ++= "\n"
    }

    val logical = all.values.flatten.filter(_.kind == "type").map(_.key).toSeq.distinct
    if (logical.nonEmpty) {
      out ++= "## Type mapping\n\n"
      out ++= "Native column type → Spark type the connector infers.\n\n"
      out ++= "| fixture type | " + engines.mkString(" | ") + " |\n|---|" + engines.map(_ => "---").mkString("|") + "|\n"
      logical.foreach { l =>
        val cells = engines.map { e =>
          all(e).find(r => r.kind == "type" && r.key == l).map(r => s"${cell(r.detail)} → ${cell(r.value)}").getOrElse("")
        }
        out ++= s"| $l | ${cells.mkString(" | ")} |\n"
      }
      out ++= "\n"
    }

    val gaps = all.toSeq.sortBy(_._1).flatMap { case (e, rs) => rs.filter(_.kind == "gap").map(e -> _) }
    out ++= "## Known gaps\n\n"
    out ++= "Tests that fail on an engine today and are cancelled with a reason instead (see each suite's `knownGaps`).\n\n"
    if (gaps.isEmpty) out ++= "None.\n"
    else {
      out ++= "| engine | test | reason | observed |\n|---|---|---|---|\n"
      gaps.foreach { case (e, r) => out ++= s"| $e | ${cell(r.key)} | ${cell(r.value)} | ${cell(r.detail)} |\n" }
    }

    Files.write(new File("target/dialect-matrix.md").toPath, out.toString.getBytes(UTF_8))
  }
}
